config/routes.rb
Errbit::Application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  # Hoptoad Notifier Routes
  match '/notifier_api/v2/notices' => 'notices#create', via: [:get, :post]
  get '/locate/:id' => 'notices#locate', :as => :locate
  post '/deploys.txt' => 'deploys#create'

  resources :notices,   :only => [:show]
  resources :deploys,   :only => [:show]
  resources :users do
    member do
      delete :unlink_github
    end
  end
  resources :problems,      :only => [:index] do
    collection do
      post :destroy_several
      post :resolve_several
      post :unresolve_several
      post :merge_several
      post :unmerge_several
      get :search
    end
  end

  resources :apps do
    resources :problems do
      resources :notices
      resources :comments, :only => [:create, :destroy]

      member do
        put :resolve
        put :unresolve
        post :create_issue
        delete :unlink_issue
      end
    end
    resources :deploys, :only => [:index]
    resources :watchers, :only => [:destroy]
    member do
      post :regenerate_api_key
    end
  end

  namespace :api do
    namespace :v1 do
      resources :problems, :only => [:index], :defaults => { :format => 'json' }
      resources :notices,  :only => [:index], :defaults => { :format => 'json' }
      resources :stats, :only => [], :defaults => { :format => 'json' } do
        collection do
          get :app
        end
      end
    end
  end

  root :to => 'apps#index'

end

app/models/user.rb
class User
  PER_PAGE = 30
  include Mongoid::Document
  include Mongoid::Timestamps

  devise *Errbit::Config.devise_modules

  field :email
  field :github_login
  field :github_oauth_token
  field :name
  field :admin, :type => Boolean, :default => false
  field :per_page, :type => Fixnum, :default => PER_PAGE
  field :time_zone, :default => "UTC"

  ## Devise field
  ### Database Authenticatable
  field :encrypted_password, :type => String

  ### Recoverable
  field :reset_password_token, :type => String
  field :reset_password_sent_at, :type => Time

  ### Rememberable
  field :remember_created_at, :type => Time

  ### Trackable
  field :sign_in_count,      :type => Integer
  field :current_sign_in_at, :type => Time
  field :last_sign_in_at,    :type => Time
  field :current_sign_in_ip, :type => String
  field :last_sign_in_ip,    :type => String

  ### Token_authenticatable
  field :authentication_token, :type => String

  index :authentication_token => 1

  before_save :ensure_authentication_token

  validates_presence_of :name
  validates_uniqueness_of :github_login, :allow_nil => true

  has_many :apps, :foreign_key => 'watchers.user_id'

  if Errbit::Config.user_has_username
    field :username
    validates_presence_of :username
  end

  def watchers
    apps.map(&:watchers).flatten.select {|w| w.user_id.to_s == id.to_s}
  end

  def per_page
    super || PER_PAGE
  end

  def watching?(app)
    apps.all.include?(app)
  end

  def password_required?
    github_login.present? ? false : super
  end

  def github_account?
    github_login.present? && github_oauth_token.present?
  end

  def can_create_github_issues?
    github_account? && Errbit::Config.github_access_scope.include?('repo')
  end

  def github_login=(login)
    if login.is_a?(String) && login.strip.empty?
      login = nil
    end
    self[:github_login] = login
  end

  def ensure_authentication_token
    if authentication_token.blank?
      self.authentication_token = generate_authentication_token
    end
  end

  def self.token_authentication_key
    :auth_token
  end

  private

  def generate_authentication_token
    loop do
      token = Devise.friendly_token
      break token unless User.where(authentication_token: token).first
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  respond_to :html

  before_filter :require_admin!, :except => [:edit, :update]
  before_filter :require_user_edit_priviledges, :only => [:edit, :update]

  expose(:user, :attributes => :user_params)
  expose(:users) {
    User.all.page(params[:page]).per(current_user.per_page)
  }

  def index; end
  def new; end
  def show; end

  def create
    if user.save
      flash[:success] = "#{user.name} is now part of the team. Be sure to add them as a project watcher."
      redirect_to user_path(user)
    else
      render :new
    end
  end

  def update
    if user.update_attributes(user_params)
      flash[:success] = I18n.t('controllers.users.flash.update.success', :name => user.name)
      redirect_to user_path(user)
    else
      render :edit
    end
  end

  ##
  # Destroy the user pass in args
  #
  # @param [ String ] id the id of user we want delete
  #
  def destroy
    if user == current_user
      flash[:error] = I18n.t('controllers.users.flash.destroy.error')
    else
      UserDestroy.new(user).destroy
      flash[:success] = I18n.t('controllers.users.flash.destroy.success', :name => user.name)
    end
    redirect_to users_path
  end

  def unlink_github
    user.update_attributes :github_login => nil, :github_oauth_token => nil
    redirect_to user_path(user)
  end

  protected

    def require_user_edit_priviledges
      can_edit = current_user == user || current_user.admin?
      redirect_to(root_path) and return(false) unless can_edit
    end

  def user_params
    @user_params ||= params[:user] ? params.require(:user).permit(*user_permit_params) : {}
  end

  def user_permit_params
    @user_permit_params ||= [:name,:username, :email, :github_login, :per_page, :time_zone]
    @user_permit_params << :admin if current_user.admin? && current_user.id != params[:id]
    @user_permit_params |= [:password, :password_confirmation] if user_password_params.values.all?{|pa| !pa.blank? }
    @user_permit_params
  end

  def user_password_params
    @user_password_params ||= params[:user] ? params.require(:user).permit(:password, :password_confirmation) : {}
  end

end

app/views/users/_fields.html.haml
= errors_for user

.required
  = f.label :name
  = f.text_field :name

- if Errbit::Config.user_has_username
  .required
    = f.label :username
    = f.text_field :username

.required
  = f.label :email
  = f.text_field :email

- if Errbit::Config.github_authentication
  = f.label :github_login
  = f.text_field :github_login

.required
  = f.label :per_page, 'Entries per page'
  = f.select :per_page, [10, 20, 30, 50, 75, 100]

.required
  = f.label :time_zone
  = f.time_zone_select :time_zone, ActiveSupport::TimeZone.us_zones

.required
  = f.label :password
  = f.password_field :password, :autocomplete => "off"

.required
  = f.label :password_confirmation
  = f.password_field :password_confirmation

- if current_user.admin?
  .checkbox
    = f.check_box :admin
    = f.label :admin, 'Admin?'

app/views/users/edit.html.haml
- content_for :title, "Edit #{user.name}"
- content_for :action_bar do
  = render 'shared/link_github_account', :user => user
  = link_to('cancel', user_path(user), :class => 'button')

= form_for user, :html => {:autocomplete => "off"} do |f|
  = user.errors.full_messages.to_sentence
  = render 'fields', :f => f

  %div.buttons= f.submit 'Update User'

app/views/users/index.html.haml
- content_for :title, 'Users'
- content_for :action_bar do
  %span= link_to('Add a New User', new_user_path, :class => 'add')

%table.users
  %thead
    %tr
      - if Errbit::Config.use_gravatar
        %th
      %th Name
      - if Errbit::Config.user_has_username
        %th Username
      %th.main Email
      %th Admin?
  %tbody
    - users.each do |user|
      %tr.user_list
        - if Errbit::Config.use_gravatar
          %td= gravatar_tag user.email, :s => 24
        %td.nowrap= link_to user.name, user_path(user)
        - if Errbit::Config.user_has_username
          %td= user.username
        %td= user.email
        %td= user.admin? ? 'Y' : 'N'
= paginate users

app/views/users/new.html.haml
- content_for :title, 'New User'
- content_for :action_bar, link_to('cancel', users_path, :class => 'button')

= form_for user do |f|

  = render 'fields', :f => f

  %div.buttons= f.submit 'Add User'

app/views/users/show.html.haml
- content_for :title, user.name

- if Errbit::Config.use_gravatar && gravatar = gravatar_url(user.email, :s => 86)
  - content_for :title_style do
    background: url('#{gravatar}') no-repeat;
    padding-left: 106px;

- content_for :action_bar do
  = render 'shared/link_github_account'
  %span= link_to('Add a New User', new_user_path, :class => 'add')
  = link_to 'edit', edit_user_path(user), :class => 'button'
  = link_to 'destroy', user_path(user), :method => :delete,
    :data => { :confirm => t('users.confirm_delete') }, :class => 'delete button'

%table.single_user
  %tr
    %th Email
    %td.main= user.email
  - if Errbit::Config.user_has_username
    %tr
      %th Username
      %td.main= user.username
  - if Errbit::Config.github_authentication && user.github_login.present?
    %tr
      %th GitHub Login
      %td.main= link_to user.github_login, "https://github.com/#{user.github_login}"
  %tr
    %th Admin?
    %td= user.admin? ? 'Y' : 'N'
  %tr
    %th Created
    %td= user.created_at.to_s(:micro)