config/routes.rb
Errbit::Application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  # Hoptoad Notifier Routes
  match '/notifier_api/v2/notices' => 'notices#create', via: [:get, :post]
  get '/locate/:id' => 'notices#locate', :as => :locate
  post '/deploys.txt' => 'deploys#create'

  resources :notices,   :only => [:show]
  resources :deploys,   :only => [:show]
  resources :users do
    member do
      delete :unlink_github
    end
  end
  resources :problems,      :only => [:index] do
    collection do
      post :destroy_several
      post :resolve_several
      post :unresolve_several
      post :merge_several
      post :unmerge_several
      get :search
    end
  end

  resources :apps do
    resources :problems do
      resources :notices
      resources :comments, :only => [:create, :destroy]

      member do
        put :resolve
        put :unresolve
        post :create_issue
        delete :unlink_issue
      end
    end
    resources :deploys, :only => [:index]
    resources :watchers, :only => [:destroy]
    member do
      post :regenerate_api_key
    end
  end

  namespace :api do
    namespace :v1 do
      resources :problems, :only => [:index], :defaults => { :format => 'json' }
      resources :notices,  :only => [:index], :defaults => { :format => 'json' }
      resources :stats, :only => [], :defaults => { :format => 'json' } do
        collection do
          get :app
        end
      end
    end
  end

  root :to => 'apps#index'

end

app/views/shared/_navigation.html.haml
#nav-bar
  %ul
    %li.apps{:class => active_if_here(:apps)}= link_to t('.apps'), apps_path
    %li.errs{:class => active_if_here(:problems)}= link_to t('.errors'), problems_path
    - if user_signed_in? && current_user.admin?
      %li.users{:class => active_if_here(:users)}= link_to t('.users'), users_path
  %div.clear

app/views/shared/_session.html.haml
- if current_user
  %ul#session-links
    %li= link_to t('.sign_out'), destroy_session_path(:user), :id => 'sign-out', :method => :delete
    %li= link_to t('.edit_profile'), edit_user_path(current_user), :id => 'edit-profile'