config/routes.rb
Errbit::Application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  # Hoptoad Notifier Routes
  match '/notifier_api/v2/notices' => 'notices#create', via: [:get, :post]
  get '/locate/:id' => 'notices#locate', :as => :locate
  post '/deploys.txt' => 'deploys#create'

  resources :notices,   :only => [:show]
  resources :deploys,   :only => [:show]
  resources :users do
    member do
      delete :unlink_github
    end
  end
  resources :problems,      :only => [:index] do
    collection do
      post :destroy_several
      post :resolve_several
      post :unresolve_several
      post :merge_several
      post :unmerge_several
      get :search
    end
  end

  resources :apps do
    resources :problems do
      resources :notices
      resources :comments, :only => [:create, :destroy]

      member do
        put :resolve
        put :unresolve
        post :create_issue
        delete :unlink_issue
      end
    end
    resources :deploys, :only => [:index]
    resources :watchers, :only => [:destroy]
    member do
      post :regenerate_api_key
    end
  end

  namespace :api do
    namespace :v1 do
      resources :problems, :only => [:index], :defaults => { :format => 'json' }
      resources :notices,  :only => [:index], :defaults => { :format => 'json' }
      resources :stats, :only => [], :defaults => { :format => 'json' } do
        collection do
          get :app
        end
      end
    end
  end

  root :to => 'apps#index'

end

app/views/apps/_configuration_instructions.html.haml
%pre
  %code
    :preserve
      # Require the airbrake gem in your App.
      # ---------------------------------------------
      #
      # Rails 3 - In your Gemfile
      # gem 'airbrake'
      #
      # Rails 2 - In environment.rb
      # config.gem 'airbrake'
      #
      # Then add the following to config/initializers/errbit.rb
      # -------------------------------------------------------

      Airbrake.configure do |config|
        config.api_key = '#{app.api_key}'
        config.host    = '#{request.host}'
        config.port    = #{request.port}
        config.secure  = config.port == 443
      end

      # Set up Javascript notifications
      # -------------------------------
      #
      # To receive notifications for javascript errors,
      # you should add <%= airbrake_javascript_notifier %> to the top of your layouts.
      #
      # Testing
      # -------
      #
      # Rails 2 - you'll need to vendor airbrake to get the rake tasks
      # rake gems:unpack GEM=airbrake
      #
      # Run:
      # rake airbrake:test
      # refresh this page

app/views/apps/_fields.html.haml
= errors_for app

%div.required
  = f.label :name
  = f.text_field :name

- unless app.new_record?
  %div
    %label Api Key
    %span= app.api_key
    = link_to t('.regenerate_api_key'), regenerate_api_key_app_path(app), :class => 'button', :method => 'post'
%div
  = f.label :repository_branch
  = f.text_field :repository_branch, :placeholder => "master"
%div
  = f.label :github_repo
  = f.text_field :github_repo, :placeholder => "errbit/errbit from https://github.com/errbit/errbit"
%div
  = f.label :bitbucket_repo
  = f.text_field :bitbucket_repo, :placeholder => "errbit/errbit from https://bitbucket.org/errbit/errbit"
%div
  = f.label :asset_host
  %em Used to generate links for JavaScript errors
  = f.text_field :asset_host, :placeholder => "e.g. https://assets.example.com"
%div
  = f.label :current_app_version, 'Latest App Version'
  %em Mobile apps can set this to ignore any error below this version. ie: 1.4.3
  = f.text_field :current_app_version, :placeholder => "e.g. 2.0.1 from the Bundle Identifier on an iOS app"
%fieldset
  %legend Notifications
  %div.checkbox
    = f.check_box :notify_on_errs, 'data-show-when-checked' => '.email_at_notices_nested'
    = f.label :notify_on_errs, 'Notify on errors'
  - if Errbit::Config.per_app_email_at_notices
    %div.email_at_notices_nested{:style => f.object.notify_on_errs ? '' : 'display: none;'}
      .field-helpertext Send a notification every
      = f.text_field :email_at_notices, :value => f.object.email_at_notices.join(", ")
      .field-helpertext times an error occurs (comma separated).
  %div.checkbox
    = f.check_box :notify_on_deploys
    = f.label :notify_on_deploys, 'Notify on deploys'

%div.checkbox
  = f.check_box :notify_all_users
  = f.label :notify_all_users, 'Send notifications to all users'


%fieldset.watchers.nested-wrapper{:style => f.object.notify_all_users ? 'display: none;' : ''}
  %legend Watchers
  = f.fields_for :watchers do |w|
    %div.watcher.nested
      %div.choose
        = w.radio_button :watcher_type, :user
        = label_tag :watcher_type_user, 'User', :for => label_for_attr(w, 'watcher_type_user')
        = w.radio_button :watcher_type, :email
        = label_tag :watcher_type_email, 'Email Address', :for => label_for_attr(w, 'watcher_type_email')
      %div.watcher_params.user{:class => w.object.email.blank? ? 'chosen' : nil}
        = w.select :user_id, User.all.map{|u| [u.name,u.id.to_s]}, :include_blank => '-- Select a User --'
      %div.watcher_params.email{:class => w.object.email.present? ? 'chosen' : nil}
        = w.text_field :email

%div.checkbox
  = f.check_box :resolve_errs_on_deploy
  = f.label :resolve_errs_on_deploy, 'Resolve errs on deploy'

= render "issue_tracker_fields", :f => f
= render "service_notification_fields", :f => f

app/views/apps/edit.html.haml
- content_for :title, 'Edit App'
- content_for :action_bar do
  = link_to_copy_attributes_from_other_app
  = link_to 'delete application', app_path(app), :method => :delete,
    :data => { :confirm => t('apps.confirm_delete') }, :class => 'button'
  = link_to('cancel', app_path(app), :class => 'button')

= form_for app do |f|

  = render 'fields', :f => f

  %div.buttons= f.submit 'Update App'

app/views/apps/index.html.haml
- content_for :title, t('.title')
- content_for :action_bar do
  %span= link_to(t('.new_app'), new_app_path, :class => 'add') if current_user.admin?

%table.apps
  %thead
    %tr
      %th= t('.name')
      - if any_github_repos? || any_bitbucket_repos?
        %th= t('.repository')
      - if any_notification_services?
        %th= t('.notify')
      - if any_issue_trackers?
        %th= t('.tracker')
      - if any_deploys?
        %th= t('.last_deploy')
      %th=t('.errors')
  %tbody
    - apps.each do |app|
      %tr
        %td.name= link_to app.name, app_path(app)
        - if any_github_repos? or any_bitbucket_repos?
          %td.github_repo
            - if app.github_repo?
              = link_to(app.github_repo, app.github_url, :target => '_blank')
            - if app.bitbucket_repo?
              = link_to(app.bitbucket_repo, app.bitbucket_url, :target => '_blank')
        - if any_notification_services?
          %td.notification_service
            - if app.notification_service_configured?
              - notification_service_img = image_tag("#{app.notification_service.label}_goto.png")
              - if app.notification_service.url
                = link_to( notification_service_img, app.notification_service.url, :target => "_blank" )
              - else
                = notification_service_img
        - if any_issue_trackers?
          %td.issue_tracker
            - if app.issue_tracker_configured?
              - tracker_img = image_tag("#{app.issue_tracker.label}_goto.png")
              - if app.issue_tracker.url
                = link_to( tracker_img, app.issue_tracker.url )
              - else
                = tracker_img
        - if any_deploys?
          %td.deploy
            - if app.last_deploy_at
              - revision = app.deploys.last.short_revision
              = link_to( app.last_deploy_at.to_s(:micro) << (revision.present? ? " (#{revision})" : ""), app_deploys_path(app))
        %td.count
          - if app.problem_count > 0
            - unresolved = app.unresolved_count
            = link_to unresolved, app_path(app), :class => (unresolved == 0 ? "resolved" : nil)
    - if apps.none?
      %tr
        %td{:colspan => 3}
          %em
            = t('.no_apps')
            = link_to t('.click_to_create'), new_app_path

app/views/apps/new.html.haml
- content_for :title, 'Add App'
- content_for :action_bar do
  = link_to_copy_attributes_from_other_app
  = link_to('cancel', apps_path, :class => 'button')

= form_for app do |f|

  = render 'fields', :f => f

  %div.buttons= f.submit 'Add App'

app/views/apps/show.html.haml
- content_for :title, app.name
- content_for :head do
  = auto_discovery_link_tag :atom, app_path(app, User.token_authentication_key => current_user.authentication_token, :format => "atom"), :title => t('.atom_title', :name => app.name, :host => request.host)
- content_for :meta do
  - if app.current_app_version.present?
    %strong="Latest App Version:"
    = app.current_app_version
  %strong=t('.errors_caught')
  = app.problems.count
  %strong=t('.deploy_count')
  = app.deploys.count
  %strong=t('.api_key')
  = app.api_key
- content_for :action_bar do
  - if current_user.admin?
    = link_to t('.edit'), edit_app_path(app), :class => 'button'
  - if all_errs
    = link_to t('.unresolved_errs'), app_path(app), :class => 'button'
  - else
    = link_to t('.all_errs'), app_path(app, :all_errs => true), :class => 'button'

  - if current_user.watching?(app)
    = link_to t('.unwatch'),  app_watcher_path({:app_id => app, :id => current_user.id}), :method => :delete, :class => 'button', :confirm => t('.are_you_sure')
%h3#watchers_toggle
  =t('.watchers')
  %span.click_span=t('.show_hide')
#watchers_div
  - if app.notify_all_users
    %table.watchers
      %thead
        %tr
          %th=t('.all_users_notified')
  - else
    %table.watchers
      %thead
        %tr
          %th=t('.user_or_email')
      %tbody
        - app.watchers.each do |watcher|
          %tr
            %td= watcher.label
        - if app.watchers.none?
          %tr
            %td
              %em= t('.no_watcher')

- if app.github_repo?
  %h3#repository_toggle
    =t('.repository')
    %span.click_span=t('.show_hide')
  #repository_div
    %table.repository
      %thead
        %tr
          %th=t('.github_repo')
      %tbody
        %tr
          %td= link_to(app.github_repo, app.github_url, :target => '_blank')

%h3#deploys_toggle
  =t('.latest_deploys')
  %span.click_span=t('.show_hide')
#deploys_div
  - if deploys.any?
    %table.deploys
      %thead
        %tr
          %th=t('.when')
          %th=t('.environment')
          %th=t('.who')
          %th=t('.message')
          %th=t('.repository')
          %th=t('.revision')

      %tbody
        - deploys.each do |deploy|
          %tr
            %td.when #{deploy.created_at.to_s(:micro)}
            %td.environment #{deploy.environment}
            %td.who #{deploy.username}
            %td.message #{deploy.message}
            %td.repository #{deploy.repository}
            %td.revision #{deploy.short_revision}
    = link_to t('.all_deploys', :count => app.deploys.count), app_deploys_path(app), :class => 'button'
  - else
    %h3=t('.no_deploys')

- if app.problems.any?
  %h3.clear=t('.errors')
  %section
    = form_tag search_problems_path(:all_errs => all_errs, :app_id => app.id), :method => :get, :remote => true do
      = text_field_tag :search, params[:search], :placeholder => t('.search_placeholder')
  %br
  %section
    .problem_table{:id => 'problem_table'}
      = render 'problems/table', :problems => problems
- else
  %h3.clear=t('.no_error_yet')
  = render 'configuration_instructions', :app => app